### ISSUE TITLE
OSC plugin parameters paths should choose "symbol", not "Name"

### ISSUE THREAD

**Issue by Houston4444** [Stazed/non-mixer-xt#2] opened 2023-02-10 13:45 UTC
This is something that already was is non-mixer (just tested), but it's maybe the opportunity to fix this.
Choose "Name" for parameters OSC paths is IMO a wrong choice.
* Many parameters could have the same name, not the same symbol
* Name is a display name, there can be space characters, which are replaced with %20, this is ugly
* Names can be translated

**Comment by Stazed** [comment] 2023-02-10 16:20
Just pushed a fix for this in the wip branch. Please test since I do not have an OSC controller to test. This uses "symbol" for LV2 only. LADSPA and internal plugins remain the same. Also if the strip or plugin name have spaces you will still get the ugly %20.

**Comment by Stazed** [comment] 2023-02-11 00:46
Got a Pd patch working to send OSC for testing and confirmed this is working. Closing.

**Closed by Stazed** 2023-02-11 00:46 UTC

**Comment by Houston4444** [comment] 2023-02-11 09:18
Thanks !
